# Generated by Django 4.0.5 on 2022-06-26 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_maestrousuario_pwd'),
    ]

    operations = [
        migrations.AddField(
            model_name='maestroproducto',
            name='imagen',
            field=models.ImageField(default='sinfoto.jpg', upload_to='images/', verbose_name='Imagen'),
        ),
    ]
