# Generated by Django 4.0.5 on 2022-06-26 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_maestroproducto_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codename', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
                ('first_name', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CoreBodegaguiadespacho',
            fields=[
                ('nrogd', models.AutoField(primary_key=True, serialize=False)),
                ('estadogd', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'core_bodegaguiadespacho',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CoreBodegastockproducto',
            fields=[
                ('idb', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'core_bodegastockproducto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CoreMaestroproducto',
            fields=[
                ('idp', models.AutoField(primary_key=True, serialize=False)),
                ('nomprod', models.CharField(max_length=100)),
                ('descprod', models.CharField(max_length=300)),
                ('precio', models.IntegerField()),
                ('imagen', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'core_maestroproducto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CoreMaestrousuario',
            fields=[
                ('rut', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('tipousu', models.CharField(max_length=50)),
                ('nomusu', models.CharField(max_length=100)),
                ('apeusu', models.CharField(max_length=100)),
                ('correo', models.CharField(max_length=100)),
                ('dirusu', models.CharField(max_length=300)),
                ('pwd', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'core_maestrousuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CorePerfilusuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(blank=True, max_length=80, null=True)),
                ('direccion', models.CharField(blank=True, max_length=80, null=True)),
            ],
            options={
                'db_table': 'core_perfilusuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CoreWebfactura',
            fields=[
                ('nrofac', models.AutoField(primary_key=True, serialize=False)),
                ('fechafac', models.DateField()),
                ('descfac', models.CharField(max_length=300)),
                ('monto', models.IntegerField()),
            ],
            options={
                'db_table': 'core_webfactura',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CoreWebsolicitudservicio',
            fields=[
                ('nross', models.AutoField(primary_key=True, serialize=False)),
                ('tiposs', models.CharField(max_length=50)),
                ('fechavisita', models.DateField()),
                ('descss', models.CharField(max_length=200)),
                ('estadoss', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'core_websolicitudservicio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('change_message', models.TextField()),
                ('action_flag', models.PositiveSmallIntegerField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
    ]
