# Generated by Django 4.0.5 on 2022-06-26 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_authgroup_authgrouppermissions_authpermission_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthGroup',
        ),
        migrations.DeleteModel(
            name='AuthGroupPermissions',
        ),
        migrations.DeleteModel(
            name='AuthPermission',
        ),
        migrations.DeleteModel(
            name='AuthUser',
        ),
        migrations.DeleteModel(
            name='AuthUserGroups',
        ),
        migrations.DeleteModel(
            name='AuthUserUserPermissions',
        ),
        migrations.DeleteModel(
            name='CoreBodegaguiadespacho',
        ),
        migrations.DeleteModel(
            name='CoreBodegastockproducto',
        ),
        migrations.DeleteModel(
            name='CoreMaestroproducto',
        ),
        migrations.DeleteModel(
            name='CoreMaestrousuario',
        ),
        migrations.DeleteModel(
            name='CorePerfilusuario',
        ),
        migrations.DeleteModel(
            name='CoreWebfactura',
        ),
        migrations.DeleteModel(
            name='CoreWebsolicitudservicio',
        ),
        migrations.DeleteModel(
            name='DjangoAdminLog',
        ),
        migrations.DeleteModel(
            name='DjangoContentType',
        ),
        migrations.DeleteModel(
            name='DjangoMigrations',
        ),
        migrations.DeleteModel(
            name='DjangoSession',
        ),
    ]
