# Generated by Django 4.0.5 on 2022-06-26 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_delete_authgroup_delete_authgrouppermissions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='websolicitudservicio',
            name='fechavisita',
        ),
        migrations.AlterField(
            model_name='webfactura',
            name='fechafac',
            field=models.CharField(max_length=50),
        ),
    ]
